//! Idempotent cell spawn, per-cell persistent lock, and worktree ownership
//! (SPEC §20.2 / §20.7 / §20.8 / §20.10). `spawn_idempotent` runs the whole
//! spawn path inside a single `BEGIN IMMEDIATE` transaction, and the audit
//! event `cell_spawn_requested` is appended + fsynced **before** any
//! consumable SQLite write. Worktree ownership rows are canonicalized, tied to
//! an existing thread, recorded (audited `worktree_created`) before filesystem
//! creation, and moved to `cleanup_requested` only via explicit audited command.
use crate::audit::{AuditChain, AuditEventDraft};
use crate::cells::EngineKind;
use crate::error::BusError;
use crate::jobs::immediate_tx;
use crate::store::Store;
use crate::threads::{CellThread, ThreadState};
use crate::types::{new_uuidv7, now_rfc3339};
use crate::validators::{validate_cell_name_allowing_ephemeral, validate_idempotency_key};
use rusqlite::params;
use std::path::{Path, PathBuf};

pub struct SpawnRequest<'a> {
    /// Principal issuing the spawn.
    pub caller: &'a str,
    /// Named cell, or `~ephemeral-…` generated by the caller handler.
    pub cell_name: &'a str,
    /// ≤128 byte (reuses the Phase 1 client idempotency bound).
    pub idempotency_key: &'a str,
    pub payload: &'a str,
}

#[derive(Debug)]
pub enum SpawnOutcome {
    Created(CellThread),
    Replayed(CellThread),
}

impl Store {
    /// SPEC §20.2 / §20.7 / §20.10: idempotent spawn. Runs inside one
    /// `BEGIN IMMEDIATE` transaction (per-cell persistent lock, no volatile
    /// mutex):
    /// 1. validate input (`E_POLICY_DENIED` on bad name/key);
    /// 2. replay — `spawn_requests(caller, cell_name, key)` hit ⇒ `Replayed`;
    /// 3. **audit `cell_spawn_requested` (append + fsync) before any mutation**;
    /// 4. per-cell lock — `INSERT OR IGNORE` into `cell_locks` + confirm row;
    /// 5. busy check — an active thread ⇒ `E_CELL_BUSY`;
    /// 6. insert `spawn_requests` + `cell_threads(spawning)` + enqueue payload.
    #[allow(clippy::too_many_arguments)]
    pub fn spawn_idempotent(
        &self,
        req: &SpawnRequest<'_>,
        engine: EngineKind,
        model: Option<&str>,
        profile: Option<&str>,
        cwd: &str,
        worktree_path: Option<&str>,
        depth_cap: u32,
        audit: &mut AuditChain,
    ) -> Result<SpawnOutcome, BusError> {
        validate_cell_name_allowing_ephemeral(req.cell_name)?;
        validate_idempotency_key(req.idempotency_key)?;
        let tx = immediate_tx(&self.0)?;
        // 1. replay
        if let Some(tid) =
            lookup_spawn_request(&self.0, req.caller, req.cell_name, req.idempotency_key)?
        {
            tx.commit()?;
            let thread = self
                .thread_get(&tid)?
                .ok_or_else(|| BusError::Internal(format!("spawn replay: missing thread {tid}")))?;
            return Ok(SpawnOutcome::Replayed(thread));
        }
        // 2. audit cell_spawn_requested BEFORE any SQLite mutation (SPEC §20.10).
        let detail = serde_json::json!({
            "caller": req.caller,
            "cell": req.cell_name,
            "idempotency_key": req.idempotency_key,
            "engine": engine.as_str(),
        });
        audit
            .append(AuditEventDraft::new(
                "cell_spawn_requested",
                None,
                Some(req.caller),
                Some(req.cell_name),
                "ok",
                Some(detail),
            ))
            .map_err(|e| BusError::Internal(format!("audit cell_spawn_requested: {e}")))?;
        // 3. per-cell persistent lock
        self.0
            .execute(
                "INSERT OR IGNORE INTO cell_locks(cell_name) VALUES (?1)",
                params![req.cell_name],
            )
            .map_err(|e| BusError::Internal(e.to_string()))?;
        let _: String = self
            .0
            .query_row(
                "SELECT cell_name FROM cell_locks WHERE cell_name = ?1",
                params![req.cell_name],
                |r| r.get(0),
            )
            .map_err(|e| BusError::Internal(e.to_string()))?;
        // 4. busy check
        if self.thread_active_for_cell(req.cell_name)?.is_some() {
            return Err(BusError::CellBusy(format!(
                "cell {} already has an active thread",
                req.cell_name
            )));
        }
        // 5. insert request + thread(spawning) + enqueued payload
        let thread_id = new_uuidv7();
        let now = now_rfc3339();
        self.0
            .execute(
                "INSERT INTO spawn_requests (caller, cell_name, idempotency_key, crewd_thread_id, created_at) VALUES (?1, ?2, ?3, ?4, ?5)",
                params![req.caller, req.cell_name, req.idempotency_key, &thread_id, &now],
            )
            .map_err(|e| BusError::Internal(e.to_string()))?;
        let thread = CellThread {
            crewd_thread_id: thread_id.clone(),
            cell_name: req.cell_name.into(),
            engine_kind: engine,
            model: model.map(|s| s.to_string()),
            profile: profile.map(|s| s.to_string()),
            engine_process_id: None,
            engine_thread_id: None,
            engine_turn_id: None,
            engine_session_id: None,
            cwd: cwd.into(),
            worktree_path: worktree_path.map(|s| s.into()),
            state: ThreadState::Spawning,
            generation: 0,
            created_by_principal: req.caller.into(),
            idempotency_key: req.idempotency_key.into(),
            created_at: now.clone(),
            updated_at: now,
        };
        self.thread_insert(&thread)?;
        self.job_enqueue_inner(&thread_id, req.cell_name, req.payload, depth_cap)?;
        tx.commit()?;
        Ok(SpawnOutcome::Created(thread))
    }

    /// SPEC §20.8: record a worktree as `created` **before** filesystem
    /// creation. The path is canonicalized (parent must exist), the owning
    /// thread must exist, and `worktree_created` is audited (append + fsync)
    /// before the SQLite insert. Duplicate canonical path → error.
    pub fn worktree_record(
        &self,
        path: &str,
        thread_id: &str,
        audit: &mut AuditChain,
    ) -> Result<(), BusError> {
        let canon = canonical_worktree_path(path)?;
        let present = self
            .0
            .query_row(
                "SELECT 1 FROM cell_threads WHERE crewd_thread_id = ?1",
                params![thread_id],
                |_| Ok(()),
            )
            .is_ok();
        if !present {
            return Err(BusError::Internal(format!(
                "worktree owner thread not found: {thread_id}"
            )));
        }
        let detail = serde_json::json!({ "path": canon, "thread": thread_id });
        audit
            .append(AuditEventDraft::new(
                "worktree_created",
                None,
                Some(thread_id),
                None,
                "ok",
                Some(detail),
            ))
            .map_err(|e| BusError::Internal(format!("audit worktree_created: {e}")))?;
        self.0
            .execute(
                "INSERT INTO worktrees (canonical_path, created_by_thread, state, created_at) VALUES (?1, ?2, 'created', ?3)",
                params![&canon, thread_id, now_rfc3339()],
            )
            .map_err(|e| BusError::Internal(e.to_string()))?;
        Ok(())
    }

    /// SPEC §20.8: mark a worktree for cleanup. Only explicit and audited
    /// (`worktree_cleanup`); never automatic.
    pub fn worktree_mark_cleanup(
        &self,
        path: &str,
        audit: &mut AuditChain,
    ) -> Result<(), BusError> {
        let canon = canonical_worktree_path(path)?;
        let present = self
            .0
            .query_row(
                "SELECT 1 FROM worktrees WHERE canonical_path = ?1",
                params![&canon],
                |_| Ok(()),
            )
            .is_ok();
        if !present {
            return Err(BusError::Internal(format!("worktree not found: {canon}")));
        }
        let detail = serde_json::json!({ "path": canon });
        audit
            .append(AuditEventDraft::new(
                "worktree_cleanup",
                None,
                None,
                None,
                "ok",
                Some(detail),
            ))
            .map_err(|e| BusError::Internal(format!("audit worktree_cleanup: {e}")))?;
        self.0
            .execute(
                "UPDATE worktrees SET state = 'cleanup_requested' WHERE canonical_path = ?1",
                params![&canon],
            )
            .map_err(|e| BusError::Internal(e.to_string()))?;
        Ok(())
    }

    pub fn worktree_list(&self) -> Result<Vec<(String, String, String)>, BusError> {
        let mut stmt = self
            .0
            .prepare("SELECT canonical_path, created_by_thread, state FROM worktrees ORDER BY canonical_path")
            .map_err(|e| BusError::Internal(e.to_string()))?;
        let rows = stmt
            .query_map([], |r| {
                Ok((
                    r.get::<_, String>(0)?,
                    r.get::<_, String>(1)?,
                    r.get::<_, String>(2)?,
                ))
            })
            .map_err(|e| BusError::Internal(e.to_string()))?;
        let mut out = Vec::new();
        for r in rows {
            out.push(r.map_err(|e| BusError::Internal(e.to_string()))?);
        }
        Ok(out)
    }
}

/// SPEC §20.2 replay lookup: `UNIQUE(caller, cell_name, idempotency_key)`.
fn lookup_spawn_request(
    conn: &rusqlite::Connection,
    caller: &str,
    cell: &str,
    key: &str,
) -> Result<Option<String>, BusError> {
    match conn.query_row(
        "SELECT crewd_thread_id FROM spawn_requests WHERE caller = ?1 AND cell_name = ?2 AND idempotency_key = ?3",
        params![caller, cell, key],
        |r| r.get::<_, String>(0),
    ) {
        Ok(id) => Ok(Some(id)),
        Err(rusqlite::Error::QueryReturnedNoRows) => Ok(None),
        Err(e) => Err(BusError::Internal(e.to_string())),
    }
}

/// SPEC §20.8: canonicalize the worktree path — resolve the existing parent to
/// its canonical absolute form and re-attach the basename. Aliases
/// (`/x/./y`, symlinks under the parent) collapse to one canonical key.
fn canonical_worktree_path(path: &str) -> Result<String, BusError> {
    let p = Path::new(path);
    let basename = p
        .file_name()
        .ok_or_else(|| BusError::Internal(format!("worktree path has no basename: {path}")))?;
    let parent = p.parent().unwrap_or_else(|| Path::new(""));
    let canon_parent: PathBuf = if parent.as_os_str().is_empty() {
        return Err(BusError::Internal(format!(
            "worktree path has no parent: {path}"
        )));
    } else {
        std::fs::canonicalize(parent).map_err(|e| {
            BusError::Internal(format!("worktree parent not canonicalizable ({path}): {e}"))
        })?
    };
    Ok(canon_parent.join(basename).to_string_lossy().into_owned())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::audit::AuditChain;
    use crate::store::Store;

    fn fresh_audit() -> (tempfile::TempDir, AuditChain) {
        let dir = tempfile::tempdir().unwrap();
        let a = AuditChain::open(&dir.path().join("a.jsonl")).unwrap();
        (dir, a)
    }

    /// Insert a real thread (no audit required for thread_insert itself).
    fn insert_thread(s: &Store, cell: &str) -> String {
        let id = new_uuidv7();
        let t = CellThread {
            crewd_thread_id: id.clone(),
            cell_name: cell.into(),
            engine_kind: EngineKind::Fake,
            model: None,
            profile: None,
            engine_process_id: None,
            engine_thread_id: None,
            engine_turn_id: None,
            engine_session_id: None,
            cwd: "/tmp/w".into(),
            worktree_path: None,
            state: ThreadState::Spawning,
            generation: 0,
            created_by_principal: "operator".into(),
            idempotency_key: new_uuidv7(),
            created_at: now_rfc3339(),
            updated_at: now_rfc3339(),
        };
        s.thread_insert(&t).unwrap();
        id
    }

    #[test]
    fn spawn_idempotency_same_thread_id() {
        let s = Store::open_in_memory().unwrap();
        let (_ad, mut audit) = fresh_audit();
        let req = SpawnRequest {
            caller: "cli:claude",
            cell_name: "glm-a",
            idempotency_key: "k1",
            payload: "do x",
        };
        let a = match s
            .spawn_idempotent(
                &req,
                EngineKind::Fake,
                None,
                None,
                "/tmp/w",
                None,
                8,
                &mut audit,
            )
            .unwrap()
        {
            SpawnOutcome::Created(t) => t,
            _ => panic!("expected Created"),
        };
        let b = match s
            .spawn_idempotent(
                &req,
                EngineKind::Fake,
                None,
                None,
                "/tmp/w",
                None,
                8,
                &mut audit,
            )
            .unwrap()
        {
            SpawnOutcome::Replayed(t) => t,
            _ => panic!("expected Replayed"),
        };
        assert_eq!(a.crewd_thread_id, b.crewd_thread_id);
        // different caller, same key → NEW thread attempt; cell is busy → E_CELL_BUSY
        let req2 = SpawnRequest {
            caller: "cli:codex",
            ..req
        };
        assert!(matches!(
            s.spawn_idempotent(&req2, EngineKind::Fake, None, None, "/tmp/w", None, 8, &mut audit),
            Err(e) if e.code() == "E_CELL_BUSY"
        ));
    }

    #[test]
    fn worktree_ownership_no_auto_delete() {
        let s = Store::open_in_memory().unwrap();
        let dir = tempfile::tempdir().unwrap();
        let parent = dir.path().join("wt");
        std::fs::create_dir_all(&parent).unwrap();
        let tid = insert_thread(&s, "c1");
        let (_ad, mut audit) = fresh_audit();
        s.worktree_record(&parent.join("x").to_string_lossy(), &tid, &mut audit)
            .unwrap();
        let l = s.worktree_list().unwrap();
        assert_eq!(l[0].2, "created");
        s.worktree_mark_cleanup(&parent.join("x").to_string_lossy(), &mut audit)
            .unwrap();
        assert_eq!(s.worktree_list().unwrap()[0].2, "cleanup_requested");
    }

    #[test]
    fn spawn_creates_enqueued_job() {
        let s = Store::open_in_memory().unwrap();
        let (_ad, mut audit) = fresh_audit();
        let req = SpawnRequest {
            caller: "cli:claude",
            cell_name: "c1",
            idempotency_key: "k1",
            payload: "do x",
        };
        let t = match s
            .spawn_idempotent(
                &req,
                EngineKind::Fake,
                None,
                None,
                "/tmp/w",
                None,
                8,
                &mut audit,
            )
            .unwrap()
        {
            SpawnOutcome::Created(t) => t,
            _ => panic!("expected Created"),
        };
        let jobs = s.jobs_for_thread(&t.crewd_thread_id).unwrap();
        assert_eq!(jobs.len(), 1);
        assert_eq!(jobs[0].payload, "do x");
        assert_eq!(jobs[0].state, crate::jobs::JobState::Queued);
    }

    #[test]
    fn worktree_record_conflict_on_duplicate_canonical_path() {
        let s = Store::open_in_memory().unwrap();
        let dir = tempfile::tempdir().unwrap();
        let parent = dir.path().join("wt");
        std::fs::create_dir_all(&parent).unwrap();
        let tid = insert_thread(&s, "c1");
        let (_ad, mut audit) = fresh_audit();
        s.worktree_record(&parent.join("dup").to_string_lossy(), &tid, &mut audit)
            .unwrap();
        assert!(s
            .worktree_record(&parent.join("dup").to_string_lossy(), &tid, &mut audit)
            .is_err());
    }

    #[test]
    fn spawn_replay_returns_thread_for_caller() {
        let s = Store::open_in_memory().unwrap();
        let (_ad, mut audit) = fresh_audit();
        let req = SpawnRequest {
            caller: "cli:claude",
            cell_name: "c2",
            idempotency_key: "rk",
            payload: "p",
        };
        let created = s
            .spawn_idempotent(
                &req,
                EngineKind::Fake,
                None,
                None,
                "/tmp/w",
                None,
                8,
                &mut audit,
            )
            .unwrap();
        let created_id = match &created {
            SpawnOutcome::Created(t) => t.crewd_thread_id.clone(),
            _ => panic!(),
        };
        s.thread_transition(&created_id, ThreadState::Running)
            .unwrap();
        s.thread_transition(&created_id, ThreadState::Done).unwrap();
        let replayed = s
            .spawn_idempotent(
                &req,
                EngineKind::Fake,
                None,
                None,
                "/tmp/w",
                None,
                8,
                &mut audit,
            )
            .unwrap();
        match replayed {
            SpawnOutcome::Replayed(t) => assert_eq!(t.crewd_thread_id, created_id),
            _ => panic!("expected Replayed after done"),
        }
    }

    // --- regression coverage ---

    #[test]
    fn spawn_rejects_invalid_name_and_key() {
        let s = Store::open_in_memory().unwrap();
        let (_ad, mut audit) = fresh_audit();
        let bad_name = SpawnRequest {
            caller: "cli",
            cell_name: "Bad/Name",
            idempotency_key: "k1",
            payload: "p",
        };
        assert_eq!(
            s.spawn_idempotent(
                &bad_name,
                EngineKind::Fake,
                None,
                None,
                "/w",
                None,
                8,
                &mut audit
            )
            .unwrap_err()
            .code(),
            "E_POLICY_DENIED"
        );
        let bad_key = SpawnRequest {
            caller: "cli",
            cell_name: "c1",
            idempotency_key: "",
            payload: "p",
        };
        assert_eq!(
            s.spawn_idempotent(
                &bad_key,
                EngineKind::Fake,
                None,
                None,
                "/w",
                None,
                8,
                &mut audit
            )
            .unwrap_err()
            .code(),
            "E_POLICY_DENIED"
        );
    }

    #[test]
    fn spawn_audit_failure_writes_no_record() {
        let dir = tempfile::tempdir().unwrap();
        let s = Store::open(&dir.path().join("s.db")).unwrap();
        let mut bad = AuditChain::open(&dir.path().join("missing").join("a.jsonl")).unwrap();
        let req = SpawnRequest {
            caller: "cli",
            cell_name: "c1",
            idempotency_key: "k1",
            payload: "p",
        };
        assert!(s
            .spawn_idempotent(
                &req,
                EngineKind::Fake,
                None,
                None,
                "/tmp/w",
                None,
                8,
                &mut bad
            )
            .is_err());
        assert!(s.thread_active_for_cell("c1").unwrap().is_none());
        assert!(s.worktree_list().unwrap().is_empty());
    }

    #[test]
    fn worktree_alias_path_collapses_to_canonical() {
        let s = Store::open_in_memory().unwrap();
        let dir = tempfile::tempdir().unwrap();
        let parent = dir.path().join("wt");
        std::fs::create_dir_all(&parent).unwrap();
        let tid = insert_thread(&s, "c1");
        let (_ad, mut audit) = fresh_audit();
        let p1 = parent.join("x");
        let p2 = parent.join(".").join("x"); // alias → same canonical
        s.worktree_record(&p1.to_string_lossy(), &tid, &mut audit)
            .unwrap();
        assert!(s
            .worktree_record(&p2.to_string_lossy(), &tid, &mut audit)
            .is_err()); // canonical-path collision
        assert_eq!(s.worktree_list().unwrap().len(), 1);
    }

    #[test]
    fn worktree_record_rejects_unknown_thread() {
        let s = Store::open_in_memory().unwrap();
        let dir = tempfile::tempdir().unwrap();
        let parent = dir.path().join("wt");
        std::fs::create_dir_all(&parent).unwrap();
        let (_ad, mut audit) = fresh_audit();
        assert!(s
            .worktree_record(
                &parent.join("x").to_string_lossy(),
                "ghost-thread",
                &mut audit,
            )
            .is_err());
        assert!(s.worktree_list().unwrap().is_empty());
    }

    #[test]
    fn worktree_record_audit_failure_writes_no_row() {
        let s = Store::open_in_memory().unwrap();
        let dir = tempfile::tempdir().unwrap();
        let parent = dir.path().join("wt");
        std::fs::create_dir_all(&parent).unwrap();
        let tid = insert_thread(&s, "c1");
        let mut bad = AuditChain::open(&dir.path().join("no").join("a.jsonl")).unwrap();
        assert!(s
            .worktree_record(&parent.join("x").to_string_lossy(), &tid, &mut bad)
            .is_err());
        assert!(s.worktree_list().unwrap().is_empty());
    }
}
